### ISSUE TITLE
Method Name is incorrect

### ISSUE THREAD

**Issue by jampot5000** [nicoriff/ORMi#1]
When attempting to use WMIMethod.ExecuteMethod with parameters. The wrong method name is selected and the calling method name is used instead.
```c#
 [WMIClass("Win32_NetworkAdapterConfiguration")]
    public class NetworkAdapterConfiguration
    {
        public string Caption { get; set; }
        public string Description { get; set; }

        public UInt32 InterfaceIndex { get; set; }

        public bool SetStatic(string ip, string netmask)
        {
            int retVal = WMIMethod.ExecuteMethod(this, new {IPAddress = new string[] {ip}, SubnetMask = new string[] {netmask}});

            if(retVal != 0)
                Console.WriteLine($"Failed to set network settings with error code {retVal}");

            return retVal == 0;
        }
    }
```

```c#
void SetupInterfaces(){
 var interfaces = helper.Query<NetworkAdapterConfiguration>()

foreach(var interface in interfaces){
    interface.SetStatic("123.123.123.123","255.255.255.0");
}
}
```

SetupInterface ends up being selected as the MethodName instead of SetStatic.

**Comment by nicoriff** [comment]
Ok. It is solved. The reflected name of the method was being captured incorrectly.

I´ll make some observations on your code:

1) foreach(var interface in interfaces)

You are using the reserved word `interface` on your foreach statement. That won´t compile. I assume you put this on the example but you are using another name.

2) In my case I do not have a `SetStatic` method. What I do have is a `EnableStatic ` one.

I´ve already pushed the corrected version. Let me know how it worked out.

**Comment by nicoriff** [comment]
Another observation is that you are using `InterfaceIndex` as the key. It seems that the CIM_KEY for that class is `Index`. I think that you´ll have to change that in order to make it work.
