### ISSUE TITLE
WindowsImpersonationContext is never disposed

### ISSUE THREAD

**Issue by chucker** [nicoriff/ORMi#10]
I noticed in the source code that a `WindowsImpersonationContext` is created in various places (both in `WMIMethod` and `WMIHelper`) and then used until the end of the method.

I'm not entirely sure if this is a problem, but it's probably cleaner to wrap it in a `using` block. ([Dispose will also Undo the impersonation.](https://referencesource.microsoft.com/#mscorlib/system/security/principal/windowsimpersonationcontext.cs,137))

**Comment by nicoriff** [comment]
I havent't noticed any memory leak related to `WindowsImpersonationContext` usage but I will monitor that. Anyway it is a good recomendation, I didn't know `WindowsImpersonationContext` implemented `IDisposable`. I will keep this issue open and follow your reccomendation on next release.

**Comment by nicoriff** [comment]
I've seen you sent a PR with all the improvements!. Just merged. Thanks!
