### ISSUE TITLE
Current package (2.0.0) doesn't appear to be optimized

### ISSUE THREAD

**Issue by chucker** [nicoriff/ORMi#12]
I got a warning in BenchmarkDotNET that the DLL appears to be a debug build, which affects performance. Is this intentional?

**Comment by nicoriff** [comment]
Hi @chucker. Yes you are right. I made that mistake a couple of versions before. I will fix it on the next release. If you need optimized ASAP you can clone and build it. Anyway there will be no big performance differences since it's small library. Thanks for advising!.
