### ISSUE TITLE
Subscribe WMI event like Get-WmiObject 

### ISSUE THREAD

**Issue by bbougot** [nicoriff/ORMi#15]
This is more a general WMI question, but I'd like to know if there is a way to subscribe events whenever a query like **Get-WmiObject Win32_PerfFormattedData_PerfOS_Processor | select PSComputerName,Name,PercentProcessorTime** is executed either locally or remotely.

**Comment by nicoriff** [comment]
So to get it clear... do you want to know whenever the query `select PSComputerName,Name,PercentProcessorTime from Win32_PerfFormattedData_PerfOS_Processor` has been executed or do you want to get notified if an instance of `Win32_PerfFormattedData_PerfOS_Processor` has been created/modified/deleted?

**Comment by bbougot** [comment]
I'm more interested in the execution of the query actually.

**Comment by nicoriff** [comment]
Take a look at this link https://www.itprotoday.com/windows-78/easier-way-view-incoming-wmi-queries

**Comment by bbougot** [comment]
Exactly what I was looking, thanks!
