### ISSUE TITLE
Issue with getting the property DelayedAutoStart on Win32_Service and Windows Server 2012R2

### ISSUE THREAD

**Issue by knekten** [nicoriff/ORMi#16]
Hi!

Doing this crashes with an exception "Invalid Query" on Windows Server 2012R2 but works fine on Windows Server 2016:
servicesTask = _wmiHelper.QueryAsync<Service>();

Service look like this:

    [WMIClass("Win32_Service")]
    public class Service : WMIInstance
    {
        public string Name { get; set; }
        public string DisplayName { get; set; }
        public string StartMode { get; set; }
        public string State { get; set; }
        public string Description { get; set; }
        public bool DelayedAutoStart { get; set; }
        public string StartName { get; set; }
        public string PathName { get; set; }
    }

If I instead query like this servicesTask = _wmiHelper.QueryAsync("SELECT * FROM Win32_Service"); it works but the dynamic objects returned doesn't contain the property "DelayedAutoStart" running on Windows Server 2012R2 but running it in 2016 includes the property though. In Windows Server 2012R2 the services can be set to Automatic and with delayed start though.

BR

Knekten

**Comment by nicoriff** [comment]
Hi @knekten. Well this seems to be a W2012 issue. I tried this on my pc running W10 and then on a W2012R2 Server:

![image](https://user-images.githubusercontent.com/15935985/62705476-dbdd8580-b9c3-11e9-9544-f55a6111a35c.png)
![image](https://user-images.githubusercontent.com/15935985/62705539-f9125400-b9c3-11e9-8c93-30fbb7c7cff1.png)

It seems that Microsoft guys added that property from W10 and W2016. Didn't know about that.
The only thing that I imagine you could do is to try to dinamically add a `WMIIgnore` attribute based on the running OS. That seems no simple task, but you could take a try on this [link](https://stackoverflow.com/questions/14663763/how-to-add-an-attribute-to-a-property-at-runtime)
