### ISSUE TITLE
Win32_Process create method

### ISSUE THREAD

**Issue by pavlovsg** [nicoriff/ORMi#19]
Can you help me with creating process with ORMi?
Something like this?

`       
[WMIClass("Win32_Process")]
        public class Win32_Process : WMIInstance
        {
            public dynamic Create(string commandLine, string currentDirectory, dynamic data, dynamic result)
            {
                return WMIMethod.ExecuteMethod(this,commandLine,currentDirectory,data,result);
            }
        }
`

**Comment by pavlovsg** [comment]
Or maybe there is something like automatic model creation for classes?

**Comment by nicoriff** [comment]
You should try something like this (never tried passing complex objects as parameters):

Define helper classes:

```
    public class ProcessResult
    {
        public int ProcessId { get; set; }
        public int ReturnValue { get; set; }
    }

    [WMIClass("Win32_ProcessStartup")]
    public class StartupInfo
    {
        
    }
```

Define the method inside your class_

```
        public ProcessResult Create(string commandLine, string currentDirectory, StartupInfo processStartupInformation)
        {
            ProcessResult res = WMIMethod.ExecuteMethod<ProcessResult>(this, new { CommandLine = commandLine, CurrentDirectory = currentDirectory, ProcessStartupInformation = processStartupInformation });
            return res;
        }
```

Note that the parameters are sent using anonymous objects: `new { CommandLine = commandLine, CurrentDirectory = currentDirectory, ProcessStartupInformation = processStartupInformation }`
