### ISSUE TITLE
Obtaining access to interface without namespace?

### ISSUE THREAD

**Issue by jdahan91** [nicoriff/ORMi#21]
I might be wrong about this (that the interface doesn't have a namespace) but I'm looking at msdn for this api and I just can't find which namespace it belongs to.

What can I do in situation like this?

https://docs.microsoft.com/en-us/windows/win32/api/audioclient/nn-audioclient-isimpleaudiovolume

**Comment by nicoriff** [comment]
Hi @jdahan91. I'm not understanding your problem. This is not WMI related. ORMi does only work with WMI.

**Comment by jdahan91** [comment]
> Hi @jdahan91. I'm not understanding your problem. This is not WMI related. ORMi does only work with WMI.

Yeah I got to this conclusion after a while.
