### ISSUE TITLE
Call static method without an instance

### ISSUE THREAD

**Issue by WizADSL** [nicoriff/ORMi#22]
I may be reading the documentation incorrectly but in the example, for executing a static method you are using a namespace that has instances.  I'm trying to call a static method on a WMI class that has only a single static method and nothing else.  If I try to use helper.query, I don't get anything back since there are no instances so I don't have a way to make the method call.  I know I'm missing something obvious but it escapes me at the moment.

**Comment by nicoriff** [comment]
You are right. Documentation is wrong. You have to call `ExecuteStaticMethod` but I found a bug just right now. I'm shipping a new version right now with bug fixed.

**Comment by WizADSL** [comment]
I can't thank you enough for such a fast response!  I did notice `ExecuteStaticMethod` but couldn't get it to work, I guess that was why.  Thanks again.

**Comment by nicoriff** [comment]
Yes. Try with the given example on Readme.MD that works. Will update to NuGet shortly after this. What are you doing COVID related?

**Comment by WizADSL** [comment]
Specifically, I'm using ORMi against SCCM to find the names of workstations people have recently logged into and to send WOL to the workstation if it appears to be off or asleep (the reason for the static method call).

**Comment by nicoriff** [comment]
Wow... great!. I'm glad it helps. Specially for anything related to make this damn COVID-19 disease madness easier. Let me know if you need anything else. Regards!.

**Comment by WizADSL** [comment]
I'm sorry I didn't take long to run into another problem.  I am now getting an "Invalid Namespace" error.

```[2020-03-31T05:01:46.420Z] Error: System.Management.ManagementException: Invalid namespace 
   at System.Management.ManagementException.ThrowWithExtendedInfo(ManagementStatus errorCode)
   at System.Management.ManagementScope.InitializeGuts(Object o)
   at System.Management.ManagementScope.Initialize()
   at System.Management.ManagementObject.Initialize(Boolean getObject)
   at System.Management.ManagementObject.GetMethodParameters(String methodName, ManagementBaseObject& inParameters, IWbemClassObjectFreeThreaded& inParametersClass, IWbemClassObjectFreeThreaded& outParametersClass)
   at ORMi.WMIMethod.ExecuteStaticMethod[T](Object parameters)```

The static method is being run on a remote machine and requires credentials.  There is an instance of the `WMIHelper` being created prior to the static method call.  Since I am creating a seemingly independent instance of a class (the one that contains the static method), other than that class is a subclass of `WMIInstance`, does the call get made using the credentials used to create WMI helper?

**Comment by nicoriff** [comment]
Hi. For static methods there is no actual way to impersonate the user other than running the application with the remote users. I assume that it should be a domain admin user or something like that. I' ll try to think a better way of doing this.
