### ISSUE TITLE
Can't run code on linux

### ISSUE THREAD

**Issue by infernalred** [nicoriff/ORMi#23]
If i publish app on linux server i get **System.Management currently is only supported for Windows desktop applications.**

**Comment by nicoriff** [comment]
There seems to be no plans to support that functionality yet. Take a look at this links:

- https://github.com/dotnet/runtime/issues/23918
- https://github.com/dotnet/runtime/issues/31576

What do you need to do?.

**Comment by infernalred** [comment]
WMI query (

**Comment by chucker** [comment]
> If i publish app on linux server

There is no WMI on Linux. Are you trying to query a Windows machine from Linux?
