### ISSUE TITLE
Implement IDisposable pattern in WMIWatcher class 

### ISSUE THREAD

**Issue by magalhaesleo** [nicoriff/ORMi#24]
The class WMIWatcher contains a field `ManagementEventWatcher` that is disposable.

It's possible change WMIWatcher to dispose the `ManagementEventWatcher` field and stop watcher for new events when the object WMIWatcher is finalized?

**Comment by nicoriff** [comment]
Hi there. Done. WMIWatcher has now support for IDisposable

**Comment by magalhaesleo** [comment]
Thanks
