### ISSUE TITLE
WMI cannot return the result, please help, thank you

### ISSUE THREAD

**Issue by simadi** [nicoriff/ORMi#30]
I use WMI to get information on a remote computer, If use Administrator, both of the following queries can return data。

 SELECT * FROM Win32_DiskDrive，
 SELECT * FROM Win32_NTLogEvent

 If  use a non-Administrator account, the data can be returned first.The second one returns zero data, I guess it is the problem of the remote computer setting, but I don't know how to do it specifically. Please help me, thank you

**Comment by nicoriff** [comment]
@simadi I do not know. I guess it is an issue with user permissions.
