### ISSUE TITLE
'System.Management 5.0.0' is not compatible with 'ORMi 3.2.0 constraint: System.Management (= 4.6.0)'.

### ISSUE THREAD

**Issue by kevwkev** [nicoriff/ORMi#33]
I am still getting this error: Unable to resolve dependencies. 'System.Management 5.0.0' is not compatible with 'ORMi 3.2.0 constraint: System.Management (= 4.6.0)'.

_Originally posted by @kevwkev in https://github.com/nicoriff/ORMi/issues/32#issuecomment-940158455_

**Comment by nicoriff** [comment]
I'm not able to reproduce the problem. Where are you getting that exception? Can you post the code?

**Comment by kevwkev** [comment]
Thank you the update. I can install the Nuget package.
