### ISSUE TITLE
Can't use async query with Helper

### ISSUE THREAD

**Issue by madjarian** [nicoriff/ORMi#35]
Hi and thank you for your work.
i try to use Ormi with async query like that:

  ```
  [WMIClass("Win32_Processor")]
    public class Processor : WMIInstance
    {
        public string Name { get; set; }
        [WMIProperty("NumberOfCores")]
        public int Cores { get; set; }
        public string Description { get; set; }
    }

WMIHelper helper = new WMIHelper("root\\CimV2", host, account, password);
List<Processor> processors = await helper.QueryAsync<Processor>().ToList();
...

```
but i got Compiler Error CS1061 with msg like: Task<IEnumerable<Form1.Processor>> no definition for ToList()...
is anybody have a idea to fix that ?

**Comment by nicoriff** [comment]
Try:

`List<Processor> processors = (await helper.QueryAsync<Processor>()).ToList();`
