### ISSUE TITLE
Implement WMIMethod.ExecuteMethod<T>

### ISSUE THREAD

**Issue by FaustoNascimento** [nicoriff/ORMi#4]
Rather than having `ExecuteMethod` return `dynamic`, change its implementation to `WMIMethod.ExecuteMethod<T>` to take advantage of generics.

**Comment by nicoriff** [comment]
Hi @FaustoNascimento. Great that you are using ORMi. I have this task on backlog just to add it. I will let you know when it´s done.

**Comment by FaustoNascimento** [comment]
nicoriff, I really like the idea of this ORM, but I have a few ideas about how to improve it. Including a shift to CIM classes and deduplication of code

**Comment by nicoriff** [comment]
Sorry for the delay. Having too much work. I´ve just pushed a version supporting ExecuteMethod<T>
